server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
datasourceUrl: jdbc:postgresql://127.0.0.1:5432/taskss
datasourceUserName: postgres
datasourcePassword: root
datasourceDriver: org.postgresql.Driver
#Kafka
springKafkaBootstrapServers: localhost:9092
appTopicFoo: foo.t

logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO
#database:
#  # the name of your JDBC driver
#  driverClass: org.postgresql.Driver
#  # the username
#  user: postgres
#  # the password
#  password: root
#  # the JDBC URL
#  url: jdbc:postgresql://localhost:5432/taskss
